import { Tag, Typography } from "antd";
import dayjs from "dayjs";
import { IoMdTime } from "react-icons/io";
import { formatMoney } from "../../../utils/util";

export const columns = ({ handleCheck, handleSelectChange }) => [
  {
    title: "ลำดับ",
    dataIndex: "ind",
    key: "ind",
    width: 60,
    render: (im, rc, index) => <>{index + 1}</>,
  },
  {
    title: "ใบขายสินค้า",
    dataIndex: "socode",
    key: "socode",
    width: 90,
    align: "right",
    className: "!pe-3",
  },
  {
    title: "รหัสสินค้า",
    dataIndex: "stcode",
    key: "stcode",
    width: 90,
    align: "left",
  },
  {
    title: "รหัสลูกค้า",
    dataIndex: "cuscode",
    key: "cuscode",
    width: 90,
    align: "left",
  },
  {
    title: "ชื่อสินค้า",
    dataIndex: "stname",
    key: "stname",
    align: "left",
    render: (_, rec) => rec.stname,
  },  
  // {
  //   title: "จำนวนสั่งซื้อ",
  //   dataIndex: "qty",
  //   key: "qty",
  // },
  // {
  //   title: "จำนวนคงเหลือหลังหัก",
  //   dataIndex: "total_qty",
  //   key: "total_qty",
  //   width: "12%",
  //   align: "right",
  //   className: "!pe-3",
  //   render: (_, rec) => <>{formatMoney(Number(rec?.total_qty || 0), 2, 2)}</>,
  // },
  // {
  //   title: "จำนวนสินค้าคงคลัง",
  //   dataIndex: "qty_stock",
  //   key: "qty_stock",
  // },
  // {
  //   title: "จำนวนจอง",
  //   dataIndex: "qty_book",
  //   key: "qty_book",
  //   width: "10%",
  //   align: "right",
  //   className: "!pe-3",
  //   render: (_, rec) => <>{formatMoney(Number(rec?.qty_book || 0), 2, 2)}</>,
  // },
  {
    title: "จำนวนที่ต้องซื้อ",
    dataIndex: "qty_result",
    key: "qty_result",
    width: "8%",
    align: "right",
    className: "!pe-3",
    editable: true,
    required: true,
    type: "number",
    render: (_, rec) => <>{formatMoney(Number(rec?.qty_result || 0), 2, 2)}</>,
  },
  {
    title: "หน่วยสินค้า",
    dataIndex: "unit",
    key: "unit",
    align: "right",
    width: "8%",
    editable: true,
    type: "select",
  },
  {
    title: "ตัวเลือก",
    align: "center",
    key: "operation",
    dataIndex: "operation",
    render: (_, record, idx) => handleCheck(record),
    width: "90px",
    fixed: "right",
  },
];